ADMIN = 'admin'
MODERATOR = 'moderator'
USER = 'user'
CHOICES = (
    (ADMIN, 'Админ'),
    (MODERATOR, 'Модератор'),
    (USER, 'Пользователь'),
)

USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
CODE_MAX_LENGTH = 6
CATEGORYNAME_MAX_LENGTH = 256
GENRENAME_MAX_LENGTH = 256
GENRESLUG_MAX_LENGTH = 50
TITLENAME_MAX_LENGTH = 256

CUT_LENGTH_TEXT = 30
